### diagnosis icd 10

In [12]:
import pandas as pd
df = pd.read_excel("SVYKHOA_dataset_diagnosis.xlsx")
df

,intruction,icd_10,icd_10/title,question,symptom,diagnosis,document/title,document/description,cme/title,cme/description
0,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",N39.3,Tiểu không kiểm soát do gắng sức ở nữ giới,Các triệu chứng điển hình của tiểu không kiểm ...,Các triệu chứng và dấu hiệu lâm sàng bao gồm: ...,Chẩn đoán tiểu không kiểm soát do gắng sức ở n...,Hướng dẫn chẩn đoán và quản lý tiểu không kiểm...,Tài liệu này cung cấp các tiêu chí chẩn đoán t...,Cập nhật chẩn đoán phân biệt và nguyên nhân gâ...,Khóa học đào tạo y khoa liên tục này nhằm nâng...
1,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",N39.3,Tiểu không kiểm soát do gắng sức ở nữ giới,Những chỉ định lâm sàng nào cho phẫu thuật TOT...,Các triệu chứng gợi ý chỉ định phẫu thuật TOT ...,Chỉ định phẫu thuật TOT được cân nhắc cho nhữn...,Nghiên cứu về chỉ định phẫu thuật TOT trong đi...,Tài liệu này trình bày các phát hiện từ một ng...,Kỹ thuật phẫu thuật TOT và quản lý biến chứng ...,Khóa học này cung cấp kiến thức chuyên sâu về ...
2,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",N39.3,Tiểu không kiểm soát do gắng sức ở nữ giới,"Tiểu không kiểm soát là gì, tần suất mắc bệnh ...","Tiểu không kiểm soát, theo định nghĩa của Hiệp...",Tiểu không kiểm soát do gắng sức là một tình t...,Dịch tễ học và tác động của tiểu không kiểm so...,"Tài liệu này nghiên cứu sâu về định nghĩa, phạ...",Phân tích gánh nặng bệnh tật và tác động tâm l...,Khóa học này tập trung vào việc đánh giá gánh ...
3,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",N39.3,Són tiểu gắng sức ở nữ giới,Són tiểu gắng sức ở nữ giới là gì và phẫu thuậ...,Bệnh nhân có biểu hiện rò rỉ nước tiểu không c...,Chẩn đoán són tiểu gắng sức ở nữ giới (ICD-10:...,Nghiên cứu về chỉ định phẫu thuật TOT điều trị...,Tài liệu này trình bày kết quả của một nghiên ...,Cập nhật chẩn đoán và điều trị són tiểu gắng s...,Khóa học CME này cung cấp kiến thức toàn diện ...
4,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",N39.3,Són tiểu gắng sức ở nữ giới,Những chỉ định và chống chỉ định cụ thể cho ph...,Bệnh nhân đã được chẩn đoán xác nhận mắc són t...,Chẩn đoán són tiểu gắng sức (ICD-10: N39.3) là...,Chỉ định phẫu thuật TOT trong điều trị són tiể...,Tài liệu này tổng hợp các hướng dẫn lâm sàng v...,Phẫu thuật nâng đỡ niệu đạo giữa: Kỹ thuật TOT...,Khóa học này tập trung chuyên sâu vào kỹ thuật...
...,...,...,...,...,...,...,...,...,...,...
30261,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",T62,NaN,"Tôi bị các triệu chứng như buồn nôn, nôn mửa v...",Các triệu chứng khởi phát cấp tính bao gồm buồ...,Chẩn đoán lâm sàng nghi ngờ ngộ độc chất độc d...,Hướng dẫn chẩn đoán và xử trí ngộ độc thực phẩ...,"Tài liệu này cung cấp các phác đồ chẩn đoán, đ...",Cập nhật kiến thức về ngộ độc thực phẩm và quả...,Khóa học trang bị cho các bác sĩ và nhân viên ...
30262,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",T62,NaN,Những dấu hiệu cảnh báo nào cho thấy tình trạn...,Các dấu hiệu cảnh báo nghiêm trọng bao gồm: số...,Chẩn đoán mức độ nặng của ngộ độc thực phẩm (I...,"Hướng dẫn chẩn đoán, điều trị và phòng ngừa cá...",Tài liệu này từ WHO và Bộ Y tế Việt Nam cung c...,Quản lý cấp cứu ngộ độc thực phẩm nặng và biến...,Khóa học tập trung vào việc nhận diện sớm các ...
30263,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",T62,NaN,"Khi bị ngộ độc thực phẩm nhẹ, tôi nên tự chăm ...",Các triệu chứng nhẹ bao gồm: buồn nôn thoáng q...,Đối với ngộ độc thực phẩm mức độ nhẹ (ICD-10: ...,Chăm sóc và xử trí ngộ độc thực phẩm tại nhà,Tài liệu hướng dẫn chi tiết về các biện pháp t...,Tư vấn dinh dưỡng và bù dịch trong ngộ độc thự...,Khóa học dành cho nhân viên y tế và tư vấn viê...
30264,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",T62,NaN,Ngộ độc thực phẩm do vi khuẩn Salmonella thườn...,Ngộ độc thực phẩm do Salmonella (có thể thuộc ...,Chẩn đoán xác định ngộ độc thực phẩm do Salmon...,Phác đồ điều trị bệnh do Salmonella của Bộ Y tế,Tài liệu hướng dẫn chi tiết về phác đồ chẩn đo...,Kiểm soát nhiễm khuẩn và phòng ngừa ngộ độc th...,Khóa học cung cấp kiến thức chuyên sâu về dịch...
30265,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",T62,NaN,Làm thế nào để phòng ngừa ngộ độc thực phẩm mộ...,"Đây là câu hỏi về phòng ngừa, không liên quan ...","Đây là câu hỏi về phòng ngừa, không liên quan ...",10 nguyên tắc vàng về an toàn thực phẩm của WHO,Tài liệu của Tổ chức Y tế Thế giới (WHO) đưa r...,Vệ sinh an toàn thực phẩm và phòng ngừa ngộ độ...,Khóa học cung cấp kiến thức toàn diện về vệ si...

In [13]:
# đếm số NaN
nan_count = df['intruction'].isna().sum()
print("Số NaN:", nan_count)

# đếm số chuỗi rỗng ''
empty_str_count = (df['intruction'] == '').sum()
print("Số chuỗi rỗng:", empty_str_count)

# tổng cộng giá trị rỗng
total_missing = nan_count + empty_str_count
print("Tổng số giá trị rỗng:", total_missing)

Số NaN: 1130
Số chuỗi rỗng: 0
Tổng số giá trị rỗng: 1130

In [14]:
most_common = df['intruction'].value_counts().idxmax()
count = df['intruction'].value_counts().max()

print("Giá trị xuất hiện nhiều nhất:", most_common)
print("Số lần xuất hiện:", count)

Giá trị xuất hiện nhiều nhất: Chatbot y khoa chuyên về y khoa, cung cấp thông tin và tư vấn lâm sàng dựa trên ICD-10.
Số lần xuất hiện: 25956

In [15]:
# thay NaN và chuỗi rỗng bằng most_common
df['intruction'] = df['intruction'].fillna(most_common)

In [16]:
df_diagnosis = df
df_diagnosis

,intruction,icd_10,icd_10/title,question,symptom,diagnosis,document/title,document/description,cme/title,cme/description
0,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",N39.3,Tiểu không kiểm soát do gắng sức ở nữ giới,Các triệu chứng điển hình của tiểu không kiểm ...,Các triệu chứng và dấu hiệu lâm sàng bao gồm: ...,Chẩn đoán tiểu không kiểm soát do gắng sức ở n...,Hướng dẫn chẩn đoán và quản lý tiểu không kiểm...,Tài liệu này cung cấp các tiêu chí chẩn đoán t...,Cập nhật chẩn đoán phân biệt và nguyên nhân gâ...,Khóa học đào tạo y khoa liên tục này nhằm nâng...
1,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",N39.3,Tiểu không kiểm soát do gắng sức ở nữ giới,Những chỉ định lâm sàng nào cho phẫu thuật TOT...,Các triệu chứng gợi ý chỉ định phẫu thuật TOT ...,Chỉ định phẫu thuật TOT được cân nhắc cho nhữn...,Nghiên cứu về chỉ định phẫu thuật TOT trong đi...,Tài liệu này trình bày các phát hiện từ một ng...,Kỹ thuật phẫu thuật TOT và quản lý biến chứng ...,Khóa học này cung cấp kiến thức chuyên sâu về ...
2,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",N39.3,Tiểu không kiểm soát do gắng sức ở nữ giới,"Tiểu không kiểm soát là gì, tần suất mắc bệnh ...","Tiểu không kiểm soát, theo định nghĩa của Hiệp...",Tiểu không kiểm soát do gắng sức là một tình t...,Dịch tễ học và tác động của tiểu không kiểm so...,"Tài liệu này nghiên cứu sâu về định nghĩa, phạ...",Phân tích gánh nặng bệnh tật và tác động tâm l...,Khóa học này tập trung vào việc đánh giá gánh ...
3,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",N39.3,Són tiểu gắng sức ở nữ giới,Són tiểu gắng sức ở nữ giới là gì và phẫu thuậ...,Bệnh nhân có biểu hiện rò rỉ nước tiểu không c...,Chẩn đoán són tiểu gắng sức ở nữ giới (ICD-10:...,Nghiên cứu về chỉ định phẫu thuật TOT điều trị...,Tài liệu này trình bày kết quả của một nghiên ...,Cập nhật chẩn đoán và điều trị són tiểu gắng s...,Khóa học CME này cung cấp kiến thức toàn diện ...
4,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",N39.3,Són tiểu gắng sức ở nữ giới,Những chỉ định và chống chỉ định cụ thể cho ph...,Bệnh nhân đã được chẩn đoán xác nhận mắc són t...,Chẩn đoán són tiểu gắng sức (ICD-10: N39.3) là...,Chỉ định phẫu thuật TOT trong điều trị són tiể...,Tài liệu này tổng hợp các hướng dẫn lâm sàng v...,Phẫu thuật nâng đỡ niệu đạo giữa: Kỹ thuật TOT...,Khóa học này tập trung chuyên sâu vào kỹ thuật...
...,...,...,...,...,...,...,...,...,...,...
30261,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",T62,NaN,"Tôi bị các triệu chứng như buồn nôn, nôn mửa v...",Các triệu chứng khởi phát cấp tính bao gồm buồ...,Chẩn đoán lâm sàng nghi ngờ ngộ độc chất độc d...,Hướng dẫn chẩn đoán và xử trí ngộ độc thực phẩ...,"Tài liệu này cung cấp các phác đồ chẩn đoán, đ...",Cập nhật kiến thức về ngộ độc thực phẩm và quả...,Khóa học trang bị cho các bác sĩ và nhân viên ...
30262,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",T62,NaN,Những dấu hiệu cảnh báo nào cho thấy tình trạn...,Các dấu hiệu cảnh báo nghiêm trọng bao gồm: số...,Chẩn đoán mức độ nặng của ngộ độc thực phẩm (I...,"Hướng dẫn chẩn đoán, điều trị và phòng ngừa cá...",Tài liệu này từ WHO và Bộ Y tế Việt Nam cung c...,Quản lý cấp cứu ngộ độc thực phẩm nặng và biến...,Khóa học tập trung vào việc nhận diện sớm các ...
30263,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",T62,NaN,"Khi bị ngộ độc thực phẩm nhẹ, tôi nên tự chăm ...",Các triệu chứng nhẹ bao gồm: buồn nôn thoáng q...,Đối với ngộ độc thực phẩm mức độ nhẹ (ICD-10: ...,Chăm sóc và xử trí ngộ độc thực phẩm tại nhà,Tài liệu hướng dẫn chi tiết về các biện pháp t...,Tư vấn dinh dưỡng và bù dịch trong ngộ độc thự...,Khóa học dành cho nhân viên y tế và tư vấn viê...
30264,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",T62,NaN,Ngộ độc thực phẩm do vi khuẩn Salmonella thườn...,Ngộ độc thực phẩm do Salmonella (có thể thuộc ...,Chẩn đoán xác định ngộ độc thực phẩm do Salmon...,Phác đồ điều trị bệnh do Salmonella của Bộ Y tế,Tài liệu hướng dẫn chi tiết về phác đồ chẩn đo...,Kiểm soát nhiễm khuẩn và phòng ngừa ngộ độc th...,Khóa học cung cấp kiến thức chuyên sâu về dịch...
30265,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",T62,NaN,Làm thế nào để phòng ngừa ngộ độc thực phẩm mộ...,"Đây là câu hỏi về phòng ngừa, không liên quan ...","Đây là câu hỏi về phòng ngừa, không liên quan ...",10 nguyên tắc vàng về an toàn thực phẩm của WHO,Tài liệu của Tổ chức Y tế Thế giới (WHO) đưa r...,Vệ sinh an toàn thực phẩm và phòng ngừa ngộ độ...,Khóa học cung cấp kiến thức toàn diện về vệ si...

In [17]:
df = pd.read_excel("../icd-10/icd10_processed.xlsx")
df

,STT CHƯƠNG,MÃ CHƯƠNG,TÊN NHÓM CHÍNH,MÃ BỆNH,TÊN BỆNH
0,I,A00-B99,Bệnh nhiễm trùng đường ruột,A00,Bệnh tả
1,I,A00-B99,Bệnh nhiễm trùng đường ruột,A00.0,"Bệnh tả do Vibrio cholerae 01, typ sinh học ch..."
2,I,A00-B99,Bệnh nhiễm trùng đường ruột,A00.1,"Bệnh tả do Vibrio cholerae 01, typ sinh học eltor"
3,I,A00-B99,Bệnh nhiễm trùng đường ruột,A00.9,"Bệnh tả, không đặc hiệu"
4,I,A00-B99,Bệnh nhiễm trùng đường ruột,A01,Bệnh thương hàn và phó thương hàn
...,...,...,...,...,...
12214,XXII,U00-U99,Kháng các thuốc kháng sinh và chống ung thư,U84.3,Kháng (các) thuốc chống lao
12215,XXII,U00-U99,Kháng các thuốc kháng sinh và chống ung thư,U84.7,Kháng đa thuốc kháng vi sinh vật
12216,XXII,U00-U99,Kháng các thuốc kháng sinh và chống ung thư,U84.8,Kháng thuốc kháng vi sinh vật xác định khác
12217,XXII,U00-U99,Kháng các thuốc kháng sinh và chống ung thư,U84.9,Kháng các thuốc kháng vi sinh vật không xác định
12218,XXII,U00-U99,Kháng các thuốc kháng sinh và chống ung thư,U85,Kháng các thuốc kháng ung thư

In [18]:
merged = df.merge(
    df_diagnosis,
    how="outer",
    left_on="MÃ BỆNH",
    right_on="icd_10"
)

In [19]:
df = merged.drop(columns=["icd_10", "icd_10/title"])

In [22]:
df = df.dropna(subset=['MÃ CHƯƠNG'])
df

,STT CHƯƠNG,MÃ CHƯƠNG,TÊN NHÓM CHÍNH,MÃ BỆNH,TÊN BỆNH,intruction,question,symptom,diagnosis,document/title,document/description,cme/title,cme/description
0,I,A00-B99,Bệnh nhiễm trùng đường ruột,A00,Bệnh tả,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",Một bệnh nhân đến khám với triệu chứng tiêu ch...,Bệnh nhân có khởi phát đột ngột tiêu chảy nhiề...,Nghi ngờ lâm sàng Bệnh tả (ICD-10 A00 - Choler...,"Hướng dẫn chẩn đoán, điều trị và phòng chống B...","Tài liệu chuyên sâu về dịch tễ học, cơ chế bện...",Cập nhật quản lý Bệnh tả: Từ chẩn đoán đến kiể...,Khóa học đào tạo y khoa liên tục (CME) dành ch...
1,I,A00-B99,Bệnh nhiễm trùng đường ruột,A00,Bệnh tả,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",Làm thế nào để nhận biết và chẩn đoán bệnh tả ...,"Bệnh nhân có tiêu chảy liên tục (>5 lần/giờ), ...",Bệnh tả có mất nước nặng (ICD-10 A00.0 - Chole...,"Hướng dẫn chẩn đoán, điều trị và phòng chống B...","Tài liệu chuyên sâu về dịch tễ học, cơ chế bện...",Cập nhật quản lý Bệnh tả: Từ chẩn đoán đến kiể...,Khóa học đào tạo y khoa liên tục (CME) dành ch...
2,I,A00-B99,Bệnh nhiễm trùng đường ruột,A00,Bệnh tả,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",Những xét nghiệm cận lâm sàng nào cần được thự...,Bệnh nhân có triệu chứng lâm sàng nghi ngờ tả ...,Xác định chẩn đoán Bệnh tả (ICD-10 A00) bằng p...,"Hướng dẫn chẩn đoán, điều trị và phòng chống B...","Tài liệu chuyên sâu về dịch tễ học, cơ chế bện...",Cập nhật quản lý Bệnh tả: Từ chẩn đoán đến kiể...,Khóa học đào tạo y khoa liên tục (CME) dành ch...
3,I,A00-B99,Bệnh nhiễm trùng đường ruột,A00,Bệnh tả,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...","Nguyên tắc điều trị bệnh tả là gì, đặc biệt tr...",Bệnh nhân được chẩn đoán xác định hoặc nghi ng...,Nguyên tắc điều trị Bệnh tả (ICD-10 A00) bao g...,"Hướng dẫn chẩn đoán, điều trị và phòng chống B...","Tài liệu chuyên sâu về dịch tễ học, cơ chế bện...",Cập nhật quản lý Bệnh tả: Từ chẩn đoán đến kiể...,Khóa học đào tạo y khoa liên tục (CME) dành ch...
4,I,A00-B99,Bệnh nhiễm trùng đường ruột,A00,Bệnh tả,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",Các biện pháp phòng ngừa và kiểm soát dịch bện...,Không có triệu chứng lâm sàng cụ thể của bệnh ...,Các biện pháp phòng ngừa và kiểm soát Bệnh tả ...,"Hướng dẫn chẩn đoán, điều trị và phòng chống B...","Tài liệu chuyên sâu về dịch tễ học, cơ chế bện...",Cập nhật quản lý Bệnh tả: Từ chẩn đoán đến kiể...,Khóa học đào tạo y khoa liên tục (CME) dành ch...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
38550,XXI,Z00-Z99,Những người có nguy cơ sức khỏe tiềm ẩn liên q...,Z99.2,Phụ thuộc chạy thận nhân tạo,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",Các chỉ số siêu âm tim nào được sử dụng để đán...,Các chỉ số siêu âm tim quan trọng để đánh giá ...,Đánh giá chức năng tâm thu và tâm trương thất ...,Nghiên cứu về tỷ lệ E/e’ và thể tích nhĩ trái ...,Nghiên cứu này cung cấp dữ liệu định lượng về ...,Siêu âm tim nâng cao: Kỹ thuật và diễn giải cá...,Khóa học trang bị kiến thức chuyên sâu về kỹ t...
38551,XXI,Z00-Z99,Những người có nguy cơ sức khỏe tiềm ẩn liên q...,Z99.2,Phụ thuộc chạy thận nhân tạo,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",Mối quan hệ giữa thể tích siêu lọc và sự thay ...,Nghiên cứu đánh giá mối tương quan giữa thể tí...,"Ở bệnh nhân lọc máu chu kỳ, thể tích siêu lọc ...",Quy trình kỹ thuật Lọc máu chu kỳ và Quản lý t...,Tài liệu này mô tả chi tiết các quy trình kỹ t...,Chiến lược Tối ưu hóa Siêu lọc và Giám sát Huy...,Khóa học này cung cấp kiến thức nâng cao về cá...
38552,XXI,Z00-Z99,Những người có nguy cơ sức khỏe tiềm ẩn liên q...,Z99.2,Phụ thuộc chạy thận nhân tạo,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",Những yếu tố nào liên quan đến suy dinh dưỡng ...,Người bệnh lọc máu chu kỳ thường đối mặt với s...,Chẩn đoán suy dinh dưỡng ở người bệnh phụ thuộ...,TÌNH TRẠNG DINH DƯỠNG VÀ MỘT SỐ YẾU TỐ LIÊN QU...,Nghiên cứu này trình bày kết quả về tỷ lệ suy ...,Chiến lược can thiệp dinh dưỡng dựa trên yếu t...,Khóa học này khám phá các yếu tố nguy cơ gây s...
38555,XXI,Z00-Z99,Những người có nguy cơ sức khỏe tiềm ẩn liên q...,Z99.8,Phụ thuộc vào các thiết bị và dụng cụ khác,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",Kỹ thuật ECMO (Oxy hóa máu qua màng ngoài cơ t...,Các triệu chứng lâm sàng cho thấy bệnh nhân cầ...,ECMO (Extracorporeal Membrane Oxygenation) là ...,Kỹ thuật Oxy hóa máu qua màng ngoài cơ thể (EC...,"Tổng quan về nguyên lý hoạt động, phân loại (V...",ECMO cơ bản: Nguyên lý và thực hành lâm sàng t...,Khóa học này cung cấp kiến thức nền tảng về kỹ...
38556,XXI,Z00-Z99,Những người có nguy cơ sức khỏe tiềm ẩn liên q...,Z99.8,Phụ thuộc vào các thiết bị và dụng cụ khác,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",Những nhóm bệnh nhân nào có nguy cơ cao mắc nh...,Các bệnh nhân có nguy cơ cao mắc nhiễm khuẩn b...,Các bệnh nhân tại khoa hồi sức tích cực được c...,THỰC TRẠNG NHIỄM KHUẨN BỆNH VIỆN TẠI CÁC KHOA ...,Nghiên cứu này làm rõ các yếu tố nguy cơ và bố...,An toàn người bệnh và phòng ngừa nhiễm khuẩn t...,Khóa học cung cấp kiến thức và kỹ năng về các ...

In [23]:
df.to_excel("svykhoa_icd10_processed.xlsx", index=False)

In [8]:
df_generated = pd.read_excel("gen_SVYKHOA_dataset_diagnosis.xlsx")

In [9]:
merged = merged.merge(
    df_generated,
    how="outer",
    left_on="MÃ BỆNH",
    right_on="icd10"
)
merged['TÊN BỆNH'] = merged['icd_10'].combine_first(merged['TÊN BỆNH'])

In [10]:
merged

,STT CHƯƠNG,MÃ CHƯƠNG,TÊN NHÓM CHÍNH,MÃ BỆNH,TÊN BỆNH,intruction_x,icd_10,icd_10/title,question_x,symptom_x,...,cme/description_x,intruction_y,question_y,icd10,symptom_y,diagnosis_y,document/title_y,document/description_y,cme/title_y,cme/description_y
0,I,A00-B99,Bệnh nhiễm trùng đường ruột,A00,Bệnh tả,NaN,NaN,NaN,NaN,NaN,...,NaN,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",Một bệnh nhân đến khám với triệu chứng tiêu ch...,A00,Bệnh nhân có khởi phát đột ngột tiêu chảy nhiề...,Nghi ngờ lâm sàng Bệnh tả (ICD-10 A00 - Choler...,"Hướng dẫn chẩn đoán, điều trị và phòng chống B...","Tài liệu chuyên sâu về dịch tễ học, cơ chế bện...",Cập nhật quản lý Bệnh tả: Từ chẩn đoán đến kiể...,Khóa học đào tạo y khoa liên tục (CME) dành ch...
1,I,A00-B99,Bệnh nhiễm trùng đường ruột,A00,Bệnh tả,NaN,NaN,NaN,NaN,NaN,...,NaN,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",Làm thế nào để nhận biết và chẩn đoán bệnh tả ...,A00,"Bệnh nhân có tiêu chảy liên tục (>5 lần/giờ), ...",Bệnh tả có mất nước nặng (ICD-10 A00.0 - Chole...,"Hướng dẫn chẩn đoán, điều trị và phòng chống B...","Tài liệu chuyên sâu về dịch tễ học, cơ chế bện...",Cập nhật quản lý Bệnh tả: Từ chẩn đoán đến kiể...,Khóa học đào tạo y khoa liên tục (CME) dành ch...
2,I,A00-B99,Bệnh nhiễm trùng đường ruột,A00,Bệnh tả,NaN,NaN,NaN,NaN,NaN,...,NaN,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",Những xét nghiệm cận lâm sàng nào cần được thự...,A00,Bệnh nhân có triệu chứng lâm sàng nghi ngờ tả ...,Xác định chẩn đoán Bệnh tả (ICD-10 A00) bằng p...,"Hướng dẫn chẩn đoán, điều trị và phòng chống B...","Tài liệu chuyên sâu về dịch tễ học, cơ chế bện...",Cập nhật quản lý Bệnh tả: Từ chẩn đoán đến kiể...,Khóa học đào tạo y khoa liên tục (CME) dành ch...
3,I,A00-B99,Bệnh nhiễm trùng đường ruột,A00,Bệnh tả,NaN,NaN,NaN,NaN,NaN,...,NaN,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...","Nguyên tắc điều trị bệnh tả là gì, đặc biệt tr...",A00,Bệnh nhân được chẩn đoán xác định hoặc nghi ng...,Nguyên tắc điều trị Bệnh tả (ICD-10 A00) bao g...,"Hướng dẫn chẩn đoán, điều trị và phòng chống B...","Tài liệu chuyên sâu về dịch tễ học, cơ chế bện...",Cập nhật quản lý Bệnh tả: Từ chẩn đoán đến kiể...,Khóa học đào tạo y khoa liên tục (CME) dành ch...
4,I,A00-B99,Bệnh nhiễm trùng đường ruột,A00,Bệnh tả,NaN,NaN,NaN,NaN,NaN,...,NaN,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",Các biện pháp phòng ngừa và kiểm soát dịch bện...,A00,Không có triệu chứng lâm sàng cụ thể của bệnh ...,Các biện pháp phòng ngừa và kiểm soát Bệnh tả ...,"Hướng dẫn chẩn đoán, điều trị và phòng chống B...","Tài liệu chuyên sâu về dịch tễ học, cơ chế bện...",Cập nhật quản lý Bệnh tả: Từ chẩn đoán đến kiể...,Khóa học đào tạo y khoa liên tục (CME) dành ch...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40499,NaN,NaN,NaN,NaN,Z98.89,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",Z98.89,Các tình trạng sau thủ thuật khác được xác địn...,Những rủi ro và thách thức về mặt thẩm mỹ đối ...,Nguy cơ tiềm ẩn bao gồm những thay đổi khó lườ...,...,Khóa học tập trung vào các kỹ thuật tiên tiến ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40500,NaN,NaN,NaN,NaN,Z98.89,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",Z98.89,Các tình trạng sau phẫu thuật đã xác định khác,Việc sử dụng vạt đùi trước ngoài (ALT flap) để...,Khuyết hổng phần mềm lớn vùng mặt cổ sau phẫu ...,...,Khóa học đào tạo y khoa liên tục về các chiến ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40501,NaN,NaN,NaN,NaN,Z98.89,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",Z98.89,Các tình trạng phẫu thuật đặc hiệu khác sau th...,Dung dịch Chlorhexidine 2% này có nồng độ và đ...,Sau các thủ thuật phẫu thuật miệng như nhổ răn...,...,Khóa học này thảo luận về việc sử dụng Chlorhe...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40502,NaN,NaN,NaN,NaN,Z98.89,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",Z98.89,Trạng thái sau phẫu thuật đặc hiệu khác,Các chỉ số về thời gian phục hồi và biến chứng...,Bệnh nhân sau phẫu thuật nội soi ung thư trực ...,...,Khóa học tập trung vào các phương pháp chăm só...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40503,NaN,NaN,NaN,NaN,NaN,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",NaN,NaN,NaN,NaN,...,Khóa học này trang bị cho bác sĩ kiến thức về ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df = merged.dropna(subset=['MÃ BỆNH'])

In [12]:
df

,STT CHƯƠNG,MÃ CHƯƠNG,TÊN NHÓM CHÍNH,MÃ BỆNH,TÊN BỆNH,intruction_x,icd_10,icd_10/title,question_x,symptom_x,...,cme/description_x,intruction_y,question_y,icd10,symptom_y,diagnosis_y,document/title_y,document/description_y,cme/title_y,cme/description_y
0,I,A00-B99,Bệnh nhiễm trùng đường ruột,A00,Bệnh tả,NaN,NaN,NaN,NaN,NaN,...,NaN,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",Một bệnh nhân đến khám với triệu chứng tiêu ch...,A00,Bệnh nhân có khởi phát đột ngột tiêu chảy nhiề...,Nghi ngờ lâm sàng Bệnh tả (ICD-10 A00 - Choler...,"Hướng dẫn chẩn đoán, điều trị và phòng chống B...","Tài liệu chuyên sâu về dịch tễ học, cơ chế bện...",Cập nhật quản lý Bệnh tả: Từ chẩn đoán đến kiể...,Khóa học đào tạo y khoa liên tục (CME) dành ch...
1,I,A00-B99,Bệnh nhiễm trùng đường ruột,A00,Bệnh tả,NaN,NaN,NaN,NaN,NaN,...,NaN,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",Làm thế nào để nhận biết và chẩn đoán bệnh tả ...,A00,"Bệnh nhân có tiêu chảy liên tục (>5 lần/giờ), ...",Bệnh tả có mất nước nặng (ICD-10 A00.0 - Chole...,"Hướng dẫn chẩn đoán, điều trị và phòng chống B...","Tài liệu chuyên sâu về dịch tễ học, cơ chế bện...",Cập nhật quản lý Bệnh tả: Từ chẩn đoán đến kiể...,Khóa học đào tạo y khoa liên tục (CME) dành ch...
2,I,A00-B99,Bệnh nhiễm trùng đường ruột,A00,Bệnh tả,NaN,NaN,NaN,NaN,NaN,...,NaN,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",Những xét nghiệm cận lâm sàng nào cần được thự...,A00,Bệnh nhân có triệu chứng lâm sàng nghi ngờ tả ...,Xác định chẩn đoán Bệnh tả (ICD-10 A00) bằng p...,"Hướng dẫn chẩn đoán, điều trị và phòng chống B...","Tài liệu chuyên sâu về dịch tễ học, cơ chế bện...",Cập nhật quản lý Bệnh tả: Từ chẩn đoán đến kiể...,Khóa học đào tạo y khoa liên tục (CME) dành ch...
3,I,A00-B99,Bệnh nhiễm trùng đường ruột,A00,Bệnh tả,NaN,NaN,NaN,NaN,NaN,...,NaN,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...","Nguyên tắc điều trị bệnh tả là gì, đặc biệt tr...",A00,Bệnh nhân được chẩn đoán xác định hoặc nghi ng...,Nguyên tắc điều trị Bệnh tả (ICD-10 A00) bao g...,"Hướng dẫn chẩn đoán, điều trị và phòng chống B...","Tài liệu chuyên sâu về dịch tễ học, cơ chế bện...",Cập nhật quản lý Bệnh tả: Từ chẩn đoán đến kiể...,Khóa học đào tạo y khoa liên tục (CME) dành ch...
4,I,A00-B99,Bệnh nhiễm trùng đường ruột,A00,Bệnh tả,NaN,NaN,NaN,NaN,NaN,...,NaN,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",Các biện pháp phòng ngừa và kiểm soát dịch bện...,A00,Không có triệu chứng lâm sàng cụ thể của bệnh ...,Các biện pháp phòng ngừa và kiểm soát Bệnh tả ...,"Hướng dẫn chẩn đoán, điều trị và phòng chống B...","Tài liệu chuyên sâu về dịch tễ học, cơ chế bện...",Cập nhật quản lý Bệnh tả: Từ chẩn đoán đến kiể...,Khóa học đào tạo y khoa liên tục (CME) dành ch...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37565,XXI,Z00-Z99,Những người có nguy cơ sức khỏe tiềm ẩn liên q...,Z99.3,Phụ thuộc vào xe lăn,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37566,XXI,Z00-Z99,Những người có nguy cơ sức khỏe tiềm ẩn liên q...,Z99.4,Lệ thuộc vào tim nhân tạo,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37567,XXI,Z00-Z99,Những người có nguy cơ sức khỏe tiềm ẩn liên q...,Z99.8,Z99.8,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",Z99.8,Phụ thuộc vào các máy và thiết bị hỗ trợ khác,Kỹ thuật ECMO (Oxy hóa máu qua màng ngoài cơ t...,Các triệu chứng lâm sàng cho thấy bệnh nhân cầ...,...,Khóa học này cung cấp kiến thức nền tảng về kỹ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37568,XXI,Z00-Z99,Những người có nguy cơ sức khỏe tiềm ẩn liên q...,Z99.8,Z99.8,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",Z99.8,"Phụ thuộc vào các máy và thiết bị hỗ trợ khác,...",Những nhóm bệnh nhân nào có nguy cơ cao mắc nh...,Các bệnh nhân có nguy cơ cao mắc nhiễm khuẩn b...,...,Khóa học cung cấp kiến thức và kỹ năng về các ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37569,XXI,Z00-Z99,Những người có nguy cơ sức khỏe tiềm ẩn liên q...,Z99.9,Phụ thuộc vào thiết bị và dụng cụ không xác định,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df = merged.dropna(subset=['MÃ BỆNH'])

In [14]:
df

,STT CHƯƠNG,MÃ CHƯƠNG,TÊN NHÓM CHÍNH,MÃ BỆNH,TÊN BỆNH,intruction_x,icd_10,icd_10/title,question_x,symptom_x,...,cme/description_x,intruction_y,question_y,icd10,symptom_y,diagnosis_y,document/title_y,document/description_y,cme/title_y,cme/description_y
0,I,A00-B99,Bệnh nhiễm trùng đường ruột,A00,Bệnh tả,NaN,NaN,NaN,NaN,NaN,...,NaN,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",Một bệnh nhân đến khám với triệu chứng tiêu ch...,A00,Bệnh nhân có khởi phát đột ngột tiêu chảy nhiề...,Nghi ngờ lâm sàng Bệnh tả (ICD-10 A00 - Choler...,"Hướng dẫn chẩn đoán, điều trị và phòng chống B...","Tài liệu chuyên sâu về dịch tễ học, cơ chế bện...",Cập nhật quản lý Bệnh tả: Từ chẩn đoán đến kiể...,Khóa học đào tạo y khoa liên tục (CME) dành ch...
1,I,A00-B99,Bệnh nhiễm trùng đường ruột,A00,Bệnh tả,NaN,NaN,NaN,NaN,NaN,...,NaN,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",Làm thế nào để nhận biết và chẩn đoán bệnh tả ...,A00,"Bệnh nhân có tiêu chảy liên tục (>5 lần/giờ), ...",Bệnh tả có mất nước nặng (ICD-10 A00.0 - Chole...,"Hướng dẫn chẩn đoán, điều trị và phòng chống B...","Tài liệu chuyên sâu về dịch tễ học, cơ chế bện...",Cập nhật quản lý Bệnh tả: Từ chẩn đoán đến kiể...,Khóa học đào tạo y khoa liên tục (CME) dành ch...
2,I,A00-B99,Bệnh nhiễm trùng đường ruột,A00,Bệnh tả,NaN,NaN,NaN,NaN,NaN,...,NaN,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",Những xét nghiệm cận lâm sàng nào cần được thự...,A00,Bệnh nhân có triệu chứng lâm sàng nghi ngờ tả ...,Xác định chẩn đoán Bệnh tả (ICD-10 A00) bằng p...,"Hướng dẫn chẩn đoán, điều trị và phòng chống B...","Tài liệu chuyên sâu về dịch tễ học, cơ chế bện...",Cập nhật quản lý Bệnh tả: Từ chẩn đoán đến kiể...,Khóa học đào tạo y khoa liên tục (CME) dành ch...
3,I,A00-B99,Bệnh nhiễm trùng đường ruột,A00,Bệnh tả,NaN,NaN,NaN,NaN,NaN,...,NaN,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...","Nguyên tắc điều trị bệnh tả là gì, đặc biệt tr...",A00,Bệnh nhân được chẩn đoán xác định hoặc nghi ng...,Nguyên tắc điều trị Bệnh tả (ICD-10 A00) bao g...,"Hướng dẫn chẩn đoán, điều trị và phòng chống B...","Tài liệu chuyên sâu về dịch tễ học, cơ chế bện...",Cập nhật quản lý Bệnh tả: Từ chẩn đoán đến kiể...,Khóa học đào tạo y khoa liên tục (CME) dành ch...
4,I,A00-B99,Bệnh nhiễm trùng đường ruột,A00,Bệnh tả,NaN,NaN,NaN,NaN,NaN,...,NaN,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",Các biện pháp phòng ngừa và kiểm soát dịch bện...,A00,Không có triệu chứng lâm sàng cụ thể của bệnh ...,Các biện pháp phòng ngừa và kiểm soát Bệnh tả ...,"Hướng dẫn chẩn đoán, điều trị và phòng chống B...","Tài liệu chuyên sâu về dịch tễ học, cơ chế bện...",Cập nhật quản lý Bệnh tả: Từ chẩn đoán đến kiể...,Khóa học đào tạo y khoa liên tục (CME) dành ch...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37565,XXI,Z00-Z99,Những người có nguy cơ sức khỏe tiềm ẩn liên q...,Z99.3,Phụ thuộc vào xe lăn,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37566,XXI,Z00-Z99,Những người có nguy cơ sức khỏe tiềm ẩn liên q...,Z99.4,Lệ thuộc vào tim nhân tạo,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37567,XXI,Z00-Z99,Những người có nguy cơ sức khỏe tiềm ẩn liên q...,Z99.8,Z99.8,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",Z99.8,Phụ thuộc vào các máy và thiết bị hỗ trợ khác,Kỹ thuật ECMO (Oxy hóa máu qua màng ngoài cơ t...,Các triệu chứng lâm sàng cho thấy bệnh nhân cầ...,...,Khóa học này cung cấp kiến thức nền tảng về kỹ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37568,XXI,Z00-Z99,Những người có nguy cơ sức khỏe tiềm ẩn liên q...,Z99.8,Z99.8,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",Z99.8,"Phụ thuộc vào các máy và thiết bị hỗ trợ khác,...",Những nhóm bệnh nhân nào có nguy cơ cao mắc nh...,Các bệnh nhân có nguy cơ cao mắc nhiễm khuẩn b...,...,Khóa học cung cấp kiến thức và kỹ năng về các ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37569,XXI,Z00-Z99,Những người có nguy cơ sức khỏe tiềm ẩn liên q...,Z99.9,Phụ thuộc vào thiết bị và dụng cụ không xác định,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [168]:
# df = df[df.isna().any(axis=1)]
df_missing = df[df['icd10'].isna() & df['icd_10'].isna()]

In [23]:
df.to_excel("SVYKHOA_dataset_diagnosis_cleaned.xlsx", index=False)

In [170]:
df_missing

,STT CHƯƠNG,MÃ CHƯƠNG,TÊN NHÓM CHÍNH,MÃ BỆNH,TÊN BỆNH,intruction_x,icd_10,icd_10/title,question_x,symptom_x,...,cme/description_x,intruction_y,question_y,icd10,symptom_y,diagnosis_y,document/title_y,document/description_y,cme/title_y,cme/description_y
1244,I,A00-B99,Bệnh nhiễm khuẩn khác,A38,Bệnh tinh hồng nhiệt,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1245,I,A00-B99,Bệnh nhiễm khuẩn khác,A39,Nhiễm trùng do não mô cầu,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1246,I,A00-B99,Bệnh nhiễm khuẩn khác,A39.0†,Viêm màng não do não mô cầu (G01*),NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1247,I,A00-B99,Bệnh nhiễm khuẩn khác,A39.1†,Hội chứng Waterhouse-Friderichsen (E35.1*),NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1248,I,A00-B99,Bệnh nhiễm khuẩn khác,A39.2,Nhiễm khuẩn huyết não mô cầu cấp tính,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36581,XXI,Z00-Z99,Những người có nguy cơ sức khỏe tiềm ẩn liên q...,Z99,Tình trạng phụ thuộc vào các thiết bị và dụng ...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36582,XXI,Z00-Z99,Những người có nguy cơ sức khỏe tiềm ẩn liên q...,Z99.0,Phụ thuộc máy hút,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36593,XXI,Z00-Z99,Những người có nguy cơ sức khỏe tiềm ẩn liên q...,Z99.3,Phụ thuộc vào xe lăn,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36594,XXI,Z00-Z99,Những người có nguy cơ sức khỏe tiềm ẩn liên q...,Z99.4,Lệ thuộc vào tim nhân tạo,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36597,XXI,Z00-Z99,Những người có nguy cơ sức khỏe tiềm ẩn liên q...,Z99.9,Phụ thuộc vào thiết bị và dụng cụ không xác định,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [171]:
import pandas as pd
import google.generativeai as genai
import time
import os
from tqdm import tqdm
import json
# Cấu hình API Key
genai.configure(api_key="AIzaSyBwVaHGxXZpSXgOz7GFcQKXZ72HeOwsKlc")  # <-- Nhớ điền API key ở đây

# Khởi tạo model
model = genai.GenerativeModel(model_name='models/gemini-2.5-flash')

# File input và output
input_file = "SVYKHOA_dataset_diagnosis_cleaned.xlsx"
output_file = "gen_SVYKHOA_dataset_diagnosis.xlsx"

# Đọc dữ liệu đầu vào
try:
    df_input = pd.read_excel(input_file)
    df_input = df_input[['TÊN NHÓM CHÍNH','MÃ BỆNH','TÊN BỆNH']].dropna().reset_index(drop=True)
    print(f"Đã đọc file Excel với {len(df_input)} dòng văn bản.")
except Exception as e:
    print(f"Lỗi khi đọc file Excel: {str(e)}")
    exit()

# Tạo DataFrame kết quả
result_columns = [
    "intruction", "question", "symptom", "diagnosis",
    "document/title",  "document/description",
    "cme/title", "cme/description"
]
if os.path.exists(output_file):
    df_result = pd.read_excel(output_file)
else:
    df_result = pd.DataFrame(columns=result_columns)

# Prompt Template mới
prompt_template = """
Bạn là một chuyên gia y tế chuyên về y khoa. Nhiệm vụ của bạn là tạo dữ liệu huấn luyện dành cho một **chatbot y khoa chuyên về y khoa** nhằm giúp chatbot phản hồi người dùng một cách chính xác, khoa học và đáng tin cậy theo chuẩn ICD-10 của Bộ Y tế Việt Nam.
Dựa vào các thông tin sau:
- TÊN NHÓM CHÍNH: {group_name}
- MÃ BỆNH: {disease_code}
- TÊN BỆNH: {disease_name}
Biết: 
- Tên nhóm chính là nhóm bệnh đại diện cho mã icd10 và loại bệnh đấy
- Mã bệnh là mã icd10 chính xác cho loại bệnh đấy
- Tên bệnh là tên bệnh chính xác cho loại bệnh đấy
Hãy sinh ra một **DANH SÁCH GỒM 5 ĐỐI TƯỢNG JSON** chứa đầy đủ TẤT CẢ các trường dưới đây. Tuyệt đối không được bỏ trống bất kỳ trường nào. Nếu đoạn văn không nêu rõ thông tin, bạn được phép **bổ sung hợp lý dựa trên kiến thức y khoa chính thống**, nhưng KHÔNG được bịa đặt hoặc sử dụng thông tin sai sự thật.
**Mục tiêu**: Dữ liệu được tạo ra sẽ được dùng để huấn luyện một **mô hình chatbot y tế**, vì vậy tất cả thông tin cần:
- Chính xác về mặt y học.
- Bám sát nội dung đoạn văn hoặc kiến thức y khoa phổ biến đã được xác thực (ví dụ: WHO, Bộ Y tế, giáo trình nha khoa).
- Có giá trị hướng dẫn, giải thích rõ ràng, có thể dùng để **tư vấn lâm sàng cho người dùng cuối**.
**Yêu cầu đặc biệt**:
- Nếu đoạn văn có đề cập đến các **chỉ số lâm sàng** như độ sâu túi lợi, chỉ số mảng bám, số răng tổn thương, mức độ đau... thì **phải đưa các con số và dữ liệu đó vào `symptom` và `diagnosis`** để tăng độ chính xác cho chatbot.
- `symptom` và `diagnosis` phải viết theo ngôn ngữ chuyên môn, **khoa học, cụ thể, không chung chung**, đủ để một bác sĩ hoặc chatbot sử dụng để diễn giải cho người bệnh.
Các trường cần điền:
- "intruction": Mô tả ngắn gọn về nhiệm vụ của chatbot, ví dụ: "Chatbot y khoa chuyên về y khoa, cung cấp thông tin và tư vấn lâm sàng dựa trên ICD-10."
- "question": Một câu hỏi y khoa phù hợp với **nội dung bài viết và câu trả lời**, tập trung vào chẩn đoán hoặc điều trị y khoa (giống như người dùng hay bác sỹ trẻ hỏi chatbot).
- "symptom": Các triệu chứng hoặc dấu hiệu lâm sàng được nêu trong bài, hoặc suy luận có cơ sở khoa học. **Bao gồm cả các chỉ số định lượng nếu có** như: túi nha chu 6mm, PI=2.2, v.v.
- "diagnosis": Chẩn đoán nha khoa chi tiết, có thể phân loại theo mức độ bệnh hoặc giai đoạn nếu phù hợp. **Phải có cơ sở y khoa vững chắc** và dùng thông số hỗ trợ chẩn đoán nếu có.
- "document/title": Tiêu đề tài liệu y khoa liên quan đến nội dung đoạn văn.
- "document/description": Mô tả ngắn gọn tài liệu tham khảo, nêu rõ mục đích hoặc giá trị ứng dụng.
- "cme/title": Tiêu đề khóa học đào tạo y khoa liên tục (CME) liên quan đến chủ đề trong đoạn văn.
- "cme/description": Mô tả ngắn về khóa học CME, giúp chatbot hiểu và phản hồi như một trợ lý học thuật chuyên ngành.
Lưu ý:- Chỉ xuất đầu ra dưới dạng đối tượng JSON hợp lệ. KHÔNG thêm bất kỳ mô tả, lời giải thích hoặc đoạn văn nào khác bên ngoài JSON.
      - Không được bổ trống bất kỳ trường nào trong đối tượng JSON.
"""



# Hàm sinh dữ liệu
def generate_with_retry(prompt, max_retries=3):
    for attempt in range(max_retries):
        try:
            response = model.generate_content(prompt)
            if response.text:
                return response
        except Exception as e:
            if attempt < max_retries - 1:
                wait_time = (attempt + 1) * 5
                print(f"Lỗi, thử lại sau {wait_time}s... (Lần {attempt + 1})")
                time.sleep(wait_time)
            else:
                print(f"Lỗi sau {max_retries} lần thử: {str(e)}")
                return None
    return None

# Hàm xử lý và lưu
def process_and_save(response, disease_code):
    try:
        cleaned = response.text.replace('```json', '').replace('```', '').strip()
        data_list = json.loads(cleaned)

        if not isinstance(data_list, list):
            raise ValueError("Kết quả không phải là danh sách JSON.")

        global df_result
        for data in data_list:
            new_row = {
                "intruction": data.get("intruction", ""),
                "question": data.get("question", ""),
                "icd10": disease_code,
                "symptom": data.get("symptom", ""),
                "diagnosis": data.get("diagnosis", ""),
                "document/title": data.get("document/title", ""),
                "document/description": data.get("document/description", ""),
                "cme/title": data.get("cme/title", ""),
                "cme/description": data.get("cme/description", "")
            }
            df_result.loc[len(df_result)] = new_row
        return True
    except Exception as e:
        print(f"\nLỗi xử lý response: {str(e)}")
        print(f"Response gốc: {response.text[:200]}...")
        return False

# Thiết lập số dòng xử lý
start_row = len(df_result)
end_row = len(df_input)
processed_count = 0
start_time = time.time()

# Vòng lặp xử lý
for index in tqdm(range(start_row, end_row)):
    row = df_input.iloc[index]
    retries = 0

    while retries < 3:
        try:
            group_name = row['TÊN NHÓM CHÍNH'].strip()
            disease_code = row['MÃ BỆNH'].strip()
            disease_name = row['TÊN BỆNH'].strip()
            prompt = prompt_template.format(
                group_name=group_name,
                disease_code=disease_code,
                disease_name=disease_name
            )
            response = generate_with_retry(prompt)

            if response and process_and_save(response, disease_code):
                processed_count += 1
                df_result.to_excel(output_file, index=False)
                time.sleep(2)
                break
            else:
                retries += 1
                print(f"Retry dòng {index} - Lần {retries}")
                time.sleep(3)

        except Exception as e:
            print(f"\nLỗi dòng {index}: {str(e)}")
            retries += 1
            time.sleep(3)

# Lưu cuốil
df_result.to_excel(output_file, index=False)
total_time = (time.time() - start_time) / 60
print(f"\nHoàn thành! Đã xử lý {processed_count} dòng.")
print(f"Thời gian chạy: {total_time:.2f} phút")
print(f"File kết quả: {output_file}")

Đã đọc file Excel với 10214 dòng văn bản.

  0%|          | 0/1813 [00:00<?, ?it/s]

Lỗi xử lý response: Invalid control character at: line 15 column 88 (char 2219)
Response gốc: ```json
[
  {
    "intruction": "Chatbot y khoa chuyên về y khoa, cung cấp thông tin và tư vấn lâm sàng dựa trên ICD-10.",
    "question": "Xin chào, mắt tôi bị dính hóa chất tẩy rửa. Mắt tôi rất đau,...
Retry dòng 8401 - Lần 1

Lỗi xử lý response: Invalid control character at: line 46 column 279 (char 9580)
Response gốc: ```json
[
  {
    "intruction": "Chatbot y khoa chuyên về y khoa, cung cấp thông tin và tư vấn lâm sàng dựa trên ICD-10.",
    "question": "Xin hỏi về các triệu chứng và chẩn đoán ban đầu của tình trạ...
Retry dòng 8401 - Lần 2

  0%|          | 5/1813 [07:04<40:44:29, 81.12s/it]

Lỗi xử lý response: Invalid control character at: line 26 column 295 (char 5490)
Response gốc: ```json
[
  {
    "intruction": "Chatbot y khoa chuyên về y khoa, cung cấp thông tin và tư vấn lâm sàng dựa trên ICD-10.",
    "question": "Triệu chứng ban đầu của ăn mòn thanh quản, khí quản và phổi ...
Retry dòng 8406 - Lần 1

  2%|▏         | 41/1813 [57:06<38:30:33, 78.24s/it]

Lỗi xử lý response: Invalid control character at: line 45 column 70 (char 8465)
Response gốc: ```json
[
  {
    "intruction": "Chatbot y khoa chuyên về y khoa, cung cấp thông tin và tư vấn lâm sàng dựa trên ICD-10.",
    "question": "Những dấu hiệu lâm sàng nào đặc trưng cho ăn mòn tổn thương ...
Retry dòng 8442 - Lần 1

  4%|▍         | 75/1813 [1:33:20<22:19:01, 46.23s/it]

Lỗi xử lý response: Invalid control character at: line 45 column 30 (char 6841)
Response gốc: ```json
[
  {
    "intruction": "Chatbot y khoa chuyên về y khoa, cung cấp thông tin và tư vấn lâm sàng dựa trên ICD-10.",
    "question": "Các dấu hiệu và triệu chứng ban đầu của tổn thương do cóng l...
Retry dòng 8476 - Lần 1

  9%|▉         | 159/1813 [2:58:10<28:56:03, 62.98s/it]

Lỗi xử lý response: Illegal trailing comma before end of object: line 10 column 205 (char 2097)
Response gốc: ```json
[
  {
    "intruction": "Chatbot y khoa chuyên về y khoa, cung cấp thông tin và tư vấn lâm sàng dựa trên ICD-10.",
    "question": "Các triệu chứng lâm sàng thường gặp của ngộ độc enzyme (T45....
Retry dòng 8560 - Lần 1

 12%|█▏        | 221/1813 [4:00:58<21:02:06, 47.57s/it]

Lỗi xử lý response: Invalid control character at: line 26 column 545 (char 6468)
Response gốc: ```json
[
  {
    "intruction": "Chatbot y khoa chuyên về y khoa, cung cấp thông tin và tư vấn lâm sàng dựa trên ICD-10.",
    "question": "Tôi có các triệu chứng như đau đầu, chóng mặt sau khi làm vi...
Retry dòng 8622 - Lần 1

 13%|█▎        | 229/1813 [4:08:22<21:22:07, 48.57s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)

 13%|█▎        | 231/1813 [4:10:12<22:35:10, 51.40s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 5.577713011s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 5
}
]
Retry dòng 8632 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 47.266136315s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 47
}
]
Retry dòng 8632 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 28.974691492s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 28
}
]
Retry dòng 8632 - Lần 3

 13%|█▎        | 232/1813 [4:11:07<23:03:24, 52.50s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 10.676664123s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 10
}
]
Retry dòng 8633 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)

 13%|█▎        | 235/1813 [4:14:04<24:54:24, 56.82s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 13.606810126s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 13
}
]
Retry dòng 8636 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 55.302417745s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 55
}
]
Retry dòng 8636 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 36.014058454s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 36
}
]
Retry dòng 8636 - Lần 3

 13%|█▎        | 236/1813 [4:15:00<24:47:14, 56.58s/it]

Lỗi, thử lại sau 5s... (Lần 1)

 13%|█▎        | 237/1813 [4:16:10<26:30:38, 60.56s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)

 13%|█▎        | 238/1813 [4:16:57<24:41:02, 56.42s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 20.453891261s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 20
}
]
Retry dòng 8639 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 1.931901383s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 1
}
]
Retry dòng 8639 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 43.647814488s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 43
}
]
Retry dòng 8639 - Lần 3

 13%|█▎        | 239/1813 [4:17:52<24:35:02, 56.23s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 25.365263569s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 25
}
]
Retry dòng 8640 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 7.101334013s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 7
}
]
Retry dòng 8640 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 48.613001404s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 48
}
]
Retry dòng 8640 - Lần 3

 13%|█▎        | 240/1813 [4:18:48<24:25:45, 55.91s/it]

Lỗi, thử lại sau 5s... (Lần 1)

 13%|█▎        | 241/1813 [4:20:45<32:24:34, 74.22s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 33.061697267s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 33
}
]
Retry dòng 8642 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 14.771507485s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 14
}
]
Retry dòng 8642 - Lần 2

 13%|█▎        | 242/1813 [4:22:10<33:47:28, 77.43s/it]

Lỗi, thử lại sau 5s... (Lần 1)

 13%|█▎        | 243/1813 [4:22:56<29:47:00, 68.29s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 20.902642651s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 20
}
]
Retry dòng 8644 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 2.061468505s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 2
}
]
Retry dòng 8644 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)

 14%|█▎        | 245/1813 [4:26:01<33:28:23, 76.85s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 16.003513722s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 16
}
]
Retry dòng 8646 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 57.18927902s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 57
}
]
Retry dòng 8646 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 38.379883492s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 38
}
]
Retry dòng 8646 - Lần 3

 14%|█▎        | 246/1813 [4:26:58<30:47:55, 70.76s/it]

Lỗi, thử lại sau 5s... (Lần 1)

 14%|█▎        | 247/1813 [4:27:48<28:07:48, 64.67s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 29.525405405s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 29
}
]
Retry dòng 8648 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 11.237612226s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 11
}
]
Retry dòng 8648 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 52.942397563s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 52
}
]
Retry dòng 8648 - Lần 3

 14%|█▎        | 248/1813 [4:28:43<26:50:24, 61.74s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 34.649947867s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 34
}
]
Retry dòng 8649 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 16.361463341s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 16
}
]
Retry dòng 8649 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 57.720999063s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 57
}
]
Retry dòng 8649 - Lần 3

 14%|█▎        | 249/1813 [4:29:38<25:58:57, 59.81s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 38.918398816s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 38
}
]
Retry dòng 8650 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 20.080886145s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 20
}
]
Retry dòng 8650 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 1.248381973s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 1
}
]
Retry dòng 8650 - Lần 3

 14%|█▍        | 250/1813 [4:30:35<25:31:19, 58.78s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 42.971032588s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 42
}
]
Retry dòng 8651 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 24.672661438s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 24
}
]
Retry dòng 8651 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 6.388509084s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 6
}
]
Retry dòng 8651 - Lần 3

 14%|█▍        | 251/1813 [4:31:30<24:59:45, 57.61s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 48.057550559s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 48
}
]
Retry dòng 8652 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 29.77914348s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 29
}
]
Retry dòng 8652 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 11.490813634s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 11
}
]
Retry dòng 8652 - Lần 3

 14%|█▍        | 252/1813 [4:32:25<24:37:33, 56.79s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 53.082319889s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 53
}
]
Retry dòng 8653 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 34.21869545s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 34
}
]
Retry dòng 8653 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 15.408861468s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 15
}
]
Retry dòng 8653 - Lần 3

 14%|█▍        | 253/1813 [4:33:21<24:31:40, 56.60s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 56.616634858s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 56
}
]
Retry dòng 8654 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 37.815523385s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 37
}
]
Retry dòng 8654 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 19.288926773s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 19
}
]
Retry dòng 8654 - Lần 3

 14%|█▍        | 254/1813 [4:34:17<24:26:24, 56.44s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 1.023279331s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 1
}
]
Retry dòng 8655 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 42.748005629s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 42
}
]
Retry dòng 8655 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 24.461658711s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 24
}
]
Retry dòng 8655 - Lần 3

 14%|█▍        | 255/1813 [4:35:12<24:12:54, 55.95s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 6.176504904s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 6
}
]
Retry dòng 8656 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 47.895619894s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 47
}
]
Retry dòng 8656 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 29.60794427s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 29
}
]
Retry dòng 8656 - Lần 3

 14%|█▍        | 256/1813 [4:36:07<24:03:25, 55.62s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 10.958482233s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 10
}
]
Retry dòng 8657 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 52.132137154s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 52
}
]
Retry dòng 8657 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 33.304828521s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 33
}
]
Retry dòng 8657 - Lần 3

 14%|█▍        | 257/1813 [4:37:03<24:08:22, 55.85s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 14.501106095s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 14
}
]
Retry dòng 8658 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 56.00394383s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 56
}
]
Retry dòng 8658 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 37.721969087s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 37
}
]
Retry dòng 8658 - Lần 3

 14%|█▍        | 258/1813 [4:37:58<24:04:50, 55.75s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 19.467186297s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 19
}
]
Retry dòng 8659 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 1.1861252s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 1
}
]
Retry dòng 8659 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 42.910974155s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 42
}
]
Retry dòng 8659 - Lần 3

 14%|█▍        | 259/1813 [4:38:53<23:56:32, 55.46s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 24.644537282s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 24
}
]
Retry dòng 8660 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 6.218964463s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 6
}
]
Retry dòng 8660 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 47.354542187s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 47
}
]
Retry dòng 8660 - Lần 3

 14%|█▍        | 260/1813 [4:39:49<23:56:54, 55.51s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 28.554543572s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 28
}
]
Retry dòng 8661 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 9.767004356s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 9
}
]
Retry dòng 8661 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 50.953015069s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 50
}
]
Retry dòng 8661 - Lần 3

 14%|█▍        | 261/1813 [4:40:45<24:02:51, 55.78s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 32.3004486s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 32
}
]
Retry dòng 8662 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 14.0357935s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 14
}
]
Retry dòng 8662 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 55.71405642s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 55
}
]
Retry dòng 8662 - Lần 3

 14%|█▍        | 262/1813 [4:41:40<23:57:11, 55.60s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 37.419165485s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 37
}
]
Retry dòng 8663 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 19.114560096s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 19
}
]
Retry dòng 8663 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 460.052783ms. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
}
]
Retry dòng 8663 - Lần 3

 15%|█▍        | 263/1813 [4:42:36<23:54:13, 55.52s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 41.633945358s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 41
}
]
Retry dòng 8664 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 22.841757954s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 22
}
]
Retry dòng 8664 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 4.045340456s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 4
}
]
Retry dòng 8664 - Lần 3

 15%|█▍        | 264/1813 [4:43:32<24:00:11, 55.79s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 45.231615195s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 45
}
]
Retry dòng 8665 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 26.317333627s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 26
}
]
Retry dòng 8665 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 8.029133729s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 8
}
]
Retry dòng 8665 - Lần 3

 15%|█▍        | 265/1813 [4:44:28<24:00:27, 55.83s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 49.723662213s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 49
}
]
Retry dòng 8666 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 31.418440611s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 31
}
]
Retry dòng 8666 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 12.988708973s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 12
}
]
Retry dòng 8666 - Lần 3

 15%|█▍        | 266/1813 [4:45:23<23:53:59, 55.62s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 54.191037184s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 54
}
]
Retry dòng 8667 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 35.39437127s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 35
}
]
Retry dòng 8667 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 16.55839811s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 16
}
]
Retry dòng 8667 - Lần 3

 15%|█▍        | 267/1813 [4:46:20<23:59:22, 55.86s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 57.768916331s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 57
}
]
Retry dòng 8668 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 38.971959664s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 38
}
]
Retry dòng 8668 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 20.188668069s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 20
}
]
Retry dòng 8668 - Lần 3

 15%|█▍        | 268/1813 [4:47:16<24:02:20, 56.01s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 1.519744431s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 1
}
]
Retry dòng 8669 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 43.219725069s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 43
}
]
Retry dòng 8669 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 24.96432187s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 24
}
]
Retry dòng 8669 - Lần 3

 15%|█▍        | 269/1813 [4:48:11<23:54:47, 55.76s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 6.683867868s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 6
}
]
Retry dòng 8670 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 48.256572548s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 48
}
]
Retry dòng 8670 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 29.417862437s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 29
}
]
Retry dòng 8670 - Lần 3

 15%|█▍        | 270/1813 [4:49:07<23:52:47, 55.71s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 10.59585005s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 10
}
]
Retry dòng 8671 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 51.792329544s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 51
}
]
Retry dòng 8671 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 33.000494623s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 33
}
]
Retry dòng 8671 - Lần 3

 15%|█▍        | 271/1813 [4:50:03<23:57:14, 55.92s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 14.145585328s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 14
}
]
Retry dòng 8672 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 55.634368269s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 55
}
]
Retry dòng 8672 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 37.37321776s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 37
}
]
Retry dòng 8672 - Lần 3

 15%|█▌        | 272/1813 [4:50:59<23:53:28, 55.81s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 19.083645703s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 19
}
]
Retry dòng 8673 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 807.022384ms. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
}
]
Retry dòng 8673 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 42.537471081s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 42
}
]
Retry dòng 8673 - Lần 3

 15%|█▌        | 273/1813 [4:51:54<23:45:02, 55.52s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 23.97017711s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 23
}
]
Retry dòng 8674 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 5.546562977s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 5
}
]
Retry dòng 8674 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)

 15%|█▌        | 274/1813 [4:53:20<27:44:48, 64.90s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 56.960555345s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 56
}
]
Retry dòng 8675 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 38.667790234s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 38
}
]
Retry dòng 8675 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 20.375319781s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 20
}
]
Retry dòng 8675 - Lần 3

 15%|█▌        | 275/1813 [4:54:16<26:30:23, 62.04s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 2.111400748s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 2
}
]
Retry dòng 8676 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 43.834562379s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 43
}
]
Retry dòng 8676 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 25.554935104s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 25
}
]
Retry dòng 8676 - Lần 3

 15%|█▌        | 276/1813 [4:55:11<25:33:46, 59.87s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 7.122013261s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 7
}
]
Retry dòng 8677 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 48.259941512s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 48
}
]
Retry dòng 8677 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 29.439876214s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 29
}
]
Retry dòng 8677 - Lần 3

 15%|█▌        | 277/1813 [4:56:07<25:04:31, 58.77s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 10.623796887s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 10
}
]
Retry dòng 8678 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 51.612003036s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 51
}
]
Retry dòng 8678 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 32.910911043s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 32
}
]
Retry dòng 8678 - Lần 3

 15%|█▌        | 278/1813 [4:57:03<24:45:47, 58.08s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 14.600570254s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 14
}
]
Retry dòng 8679 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 56.321541668s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 56
}
]
Retry dòng 8679 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 38.04871585s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 38
}
]
Retry dòng 8679 - Lần 3

 15%|█▌        | 279/1813 [4:57:58<24:20:10, 57.11s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 19.766192098s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 19
}
]
Retry dòng 8680 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 1.472544906s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 1
}
]
Retry dòng 8680 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 43.038751403s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 43
}
]
Retry dòng 8680 - Lần 3

 15%|█▌        | 280/1813 [4:58:53<24:03:39, 56.50s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 24.167807266s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 24
}
]
Retry dòng 8681 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 5.353113165s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 5
}
]
Retry dòng 8681 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 46.55841624s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 46
}
]
Retry dòng 8681 - Lần 3

 15%|█▌        | 281/1813 [4:59:50<24:02:34, 56.50s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 27.686579763s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 27
}
]
Retry dòng 8682 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 9.320512364s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 9
}
]
Retry dòng 8682 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 51.053172727s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 51
}
]
Retry dòng 8682 - Lần 3

 16%|█▌        | 282/1813 [5:00:45<23:53:25, 56.18s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 32.777141151s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 32
}
]
Retry dòng 8683 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 14.499112782s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 14
}
]
Retry dòng 8683 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 56.225227361s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 56
}
]
Retry dòng 8683 - Lần 3

 16%|█▌        | 283/1813 [5:01:40<23:42:09, 55.77s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 37.798596322s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 37
}
]
Retry dòng 8684 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 18.927539729s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 18
}
]
Retry dòng 8684 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 117.026639ms. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
}
]
Retry dòng 8684 - Lần 3

 16%|█▌        | 284/1813 [5:02:36<23:44:23, 55.90s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 40.948038981s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 40
}
]
Retry dòng 8685 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 22.147832152s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 22
}
]
Retry dòng 8685 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 3.212722712s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 3
}
]
Retry dòng 8685 - Lần 3

 16%|█▌        | 285/1813 [5:03:33<23:50:38, 56.18s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 44.945600466s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 44
}
]
Retry dòng 8686 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 26.661183545s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 26
}
]
Retry dòng 8686 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 8.361395666s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 8
}
]
Retry dòng 8686 - Lần 3

 16%|█▌        | 286/1813 [5:04:28<23:39:35, 55.78s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 50.086489287s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 50
}
]
Retry dòng 8687 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 31.31590072s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 31
}
]
Retry dòng 8687 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 12.466773213s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 12
}
]
Retry dòng 8687 - Lần 3

 16%|█▌        | 287/1813 [5:05:24<23:40:06, 55.84s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 53.659819594s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 53
}
]
Retry dòng 8688 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 34.850950104s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 34
}
]
Retry dòng 8688 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 16.046418982s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 16
}
]
Retry dòng 8688 - Lần 3

 16%|█▌        | 288/1813 [5:06:20<23:43:36, 56.01s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 57.546652594s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 57
}
]
Retry dòng 8689 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 39.271125516s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 39
}
]
Retry dòng 8689 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 20.969782037s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 20
}
]
Retry dòng 8689 - Lần 3

 16%|█▌        | 289/1813 [5:07:15<23:35:00, 55.71s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 2.654551119s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 2
}
]
Retry dòng 8690 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 44.229042123s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 44
}
]
Retry dòng 8690 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 25.381388739s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 25
}
]
Retry dòng 8690 - Lần 3

 16%|█▌        | 290/1813 [5:08:11<23:33:46, 55.70s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 6.57452594s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 6
}
]
Retry dòng 8691 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 47.768704368s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 47
}
]
Retry dòng 8691 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 28.983162979s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 28
}
]
Retry dòng 8691 - Lần 3

 16%|█▌        | 291/1813 [5:09:07<23:38:05, 55.90s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 10.317024734s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 10
}
]
Retry dòng 8692 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 52.058218053s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 52
}
]
Retry dòng 8692 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 33.790023423s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 33
}
]
Retry dòng 8692 - Lần 3

 16%|█▌        | 292/1813 [5:10:02<23:31:15, 55.67s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 15.519721191s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 15
}
]
Retry dòng 8693 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 57.25759103s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 57
}
]
Retry dòng 8693 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 38.624930894s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 38
}
]
Retry dòng 8693 - Lần 3

 16%|█▌        | 293/1813 [5:10:58<23:27:02, 55.54s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 19.795226857s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 19
}
]
Retry dòng 8694 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 977.412247ms. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
}
]
Retry dòng 8694 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 42.170073122s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 42
}
]
Retry dòng 8694 - Lần 3

 16%|█▌        | 294/1813 [5:11:54<23:33:01, 55.81s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 23.320576718s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 23
}
]
Retry dòng 8695 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 4.481680604s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 4
}
]
Retry dòng 8695 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 46.19893002s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 46
}
]
Retry dòng 8695 - Lần 3

 16%|█▋        | 295/1813 [5:12:50<23:32:51, 55.84s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 27.904654071s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 27
}
]
Retry dòng 8696 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 9.63191333s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 9
}
]
Retry dòng 8696 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 51.339759648s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 51
}
]
Retry dòng 8696 - Lần 3

 16%|█▋        | 296/1813 [5:13:45<23:24:20, 55.54s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 32.917490363s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 32
}
]
Retry dòng 8697 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 14.077739042s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 14
}
]
Retry dòng 8697 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 55.2487571s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 55
}
]
Retry dòng 8697 - Lần 3

 16%|█▋        | 297/1813 [5:14:41<23:28:09, 55.73s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 36.432801762s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 36
}
]
Retry dòng 8698 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 17.62256745s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 17
}
]
Retry dòng 8698 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 58.79446088s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 58
}
]
Retry dòng 8698 - Lần 3

 16%|█▋        | 298/1813 [5:15:37<23:32:08, 55.93s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 40.518812167s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 40
}
]
Retry dòng 8699 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 22.264382048s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 22
}
]
Retry dòng 8699 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 3.994429914s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 3
}
]
Retry dòng 8699 - Lần 3

 16%|█▋        | 299/1813 [5:16:32<23:22:38, 55.59s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 45.706704118s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 45
}
]
Retry dòng 8700 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 27.448652874s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 27
}
]
Retry dòng 8700 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 9.204796382s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 9
}
]
Retry dòng 8700 - Lần 3

 17%|█▋        | 300/1813 [5:17:27<23:15:43, 55.35s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 50.379132054s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 50
}
]
Retry dòng 8701 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 31.561071887s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 31
}
]
Retry dòng 8701 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 12.843198751s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 12
}
]
Retry dòng 8701 - Lần 3

 17%|█▋        | 301/1813 [5:18:23<23:22:25, 55.65s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 54.571329541s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 54
}
]
Retry dòng 8702 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 36.297237129s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 36
}
]
Retry dòng 8702 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 18.035799877s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 18
}
]
Retry dòng 8702 - Lần 3

 17%|█▋        | 302/1813 [5:19:18<23:15:08, 55.40s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 59.736309566s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 59
}
]
Retry dòng 8703 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 41.474302758s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 41
}
]
Retry dòng 8703 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 23.207736381s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 23
}
]
Retry dòng 8703 - Lần 3

 17%|█▋        | 303/1813 [5:20:13<23:09:53, 55.23s/it]

Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 4.557013788s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 4
}
]
Retry dòng 8704 - Lần 1
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 45.739512785s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 45
}
]
Retry dòng 8704 - Lần 2
Lỗi, thử lại sau 5s... (Lần 1)
Lỗi, thử lại sau 10s... (Lần 2)
Lỗi sau 3 lần thử: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 27.160505435s. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 250
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 27
}
]
Retry dòng 8704 - Lần 3

 17%|█▋        | 304/1813 [5:21:09<23:15:09, 55.47s/it]

Lỗi, thử lại sau 5s... (Lần 1)

 17%|█▋        | 304/1813 [5:21:14<26:34:35, 63.40s/it]

KeyboardInterrupt: