### diagnosis icd 10

In [14]:
import pandas as pd
df = pd.read_excel("../generate_dataset/SVYKHOA_dataset_diagnosis.xlsx")
df

,intruction,icd_10,icd_10/title,question,symptom,diagnosis,document/title,document/description,cme/title,cme/description
0,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",N39.3,Tiểu không kiểm soát do gắng sức ở nữ giới,Các triệu chứng điển hình của tiểu không kiểm ...,Các triệu chứng và dấu hiệu lâm sàng bao gồm: ...,Chẩn đoán tiểu không kiểm soát do gắng sức ở n...,Hướng dẫn chẩn đoán và quản lý tiểu không kiểm...,Tài liệu này cung cấp các tiêu chí chẩn đoán t...,Cập nhật chẩn đoán phân biệt và nguyên nhân gâ...,Khóa học đào tạo y khoa liên tục này nhằm nâng...
1,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",N39.3,Tiểu không kiểm soát do gắng sức ở nữ giới,Những chỉ định lâm sàng nào cho phẫu thuật TOT...,Các triệu chứng gợi ý chỉ định phẫu thuật TOT ...,Chỉ định phẫu thuật TOT được cân nhắc cho nhữn...,Nghiên cứu về chỉ định phẫu thuật TOT trong đi...,Tài liệu này trình bày các phát hiện từ một ng...,Kỹ thuật phẫu thuật TOT và quản lý biến chứng ...,Khóa học này cung cấp kiến thức chuyên sâu về ...
2,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",N39.3,Tiểu không kiểm soát do gắng sức ở nữ giới,"Tiểu không kiểm soát là gì, tần suất mắc bệnh ...","Tiểu không kiểm soát, theo định nghĩa của Hiệp...",Tiểu không kiểm soát do gắng sức là một tình t...,Dịch tễ học và tác động của tiểu không kiểm so...,"Tài liệu này nghiên cứu sâu về định nghĩa, phạ...",Phân tích gánh nặng bệnh tật và tác động tâm l...,Khóa học này tập trung vào việc đánh giá gánh ...
3,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",N39.3,Són tiểu gắng sức ở nữ giới,Són tiểu gắng sức ở nữ giới là gì và phẫu thuậ...,Bệnh nhân có biểu hiện rò rỉ nước tiểu không c...,Chẩn đoán són tiểu gắng sức ở nữ giới (ICD-10:...,Nghiên cứu về chỉ định phẫu thuật TOT điều trị...,Tài liệu này trình bày kết quả của một nghiên ...,Cập nhật chẩn đoán và điều trị són tiểu gắng s...,Khóa học CME này cung cấp kiến thức toàn diện ...
4,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",N39.3,Són tiểu gắng sức ở nữ giới,Những chỉ định và chống chỉ định cụ thể cho ph...,Bệnh nhân đã được chẩn đoán xác nhận mắc són t...,Chẩn đoán són tiểu gắng sức (ICD-10: N39.3) là...,Chỉ định phẫu thuật TOT trong điều trị són tiể...,Tài liệu này tổng hợp các hướng dẫn lâm sàng v...,Phẫu thuật nâng đỡ niệu đạo giữa: Kỹ thuật TOT...,Khóa học này tập trung chuyên sâu vào kỹ thuật...
...,...,...,...,...,...,...,...,...,...,...
20645,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",D76.3,Các hội chứng mô bào khác,Đặc điểm mô bệnh học và các dấu ấn hóa mô miễn...,"Bệnh nhân nam, 54 tuổi, có tổn thương nốt đỏ b...",Chẩn đoán bệnh Rosai-Dorfman nguyên phát của d...,BỆNH ROSAI -DORFMAN NGUYÊN PHÁT CỦA DA VÙNG LƯ...,Bài báo cáo trường hợp lâm sàng về bệnh Rosai-...,Ứng dụng hóa mô miễn dịch trong chẩn đoán phân...,Khóa học này cung cấp cái nhìn tổng quan và ch...
20646,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",D76.3,Các hội chứng mô bào khác,Bệnh Rosai-Dorfman nguyên phát của da thường đ...,Bệnh nhân nam 54 tuổi với tổn thương dạng nốt ...,Sau khi chẩn đoán xác định bệnh Rosai-Dorfman ...,BỆNH ROSAI -DORFMAN NGUYÊN PHÁT CỦA DA VÙNG LƯ...,Báo cáo trường hợp lâm sàng minh họa một ca bệ...,Tiếp cận điều trị và tiên lượng các thể bệnh R...,Khóa học này khám phá các phương pháp điều trị...
20647,NaN,D76.3,Các hội chứng mô bào khác,Làm thế nào để chẩn đoán bệnh Rosai-Dorfman ng...,"Tổn thương da (nốt, mảng, sẩn) ảnh hưởng lớp b...",Chẩn đoán xác định bệnh Rosai-Dorfman nguyên p...,Đặc điểm mô bệnh học và hóa mô miễn dịch trong...,Tài liệu này trình bày chi tiết các tiêu chí c...,Tiếp cận chẩn đoán mô bệnh học và hóa mô miễn ...,Khóa học đào tạo y khoa liên tục này cung cấp ...
20648,NaN,D76.3,Các hội chứng mô bào khác,Bệnh Rosai-Dorfman nguyên phát ở da khác biệt ...,Đối với Rosai-Dorfman nguyên phát ở da: tuổi t...,Bệnh Rosai-Dorfman nguyên phát ở da được phân ...,"Phân loại và đặc điểm dịch tễ, lâm sàng của cá...",Tài liệu này phân tích sự khác biệt về dịch tễ...,Cập nhật phân loại và chiến lược chẩn đoán phâ...,Khóa học cung cấp cái nhìn tổng quan về hệ thố...
20649,NaN,D76.3,Các hội chứng mô bào khác,Sau khi chẩn đoán bệnh Rosai-Dorfman nguyên ph...,"Bệnh nhân có tổn thương da dạng nốt, mảng hoặc...",Chẩn đoán bệnh Rosai-Dorfman nguyên phát ở da ...,Kết quả điều trị phẫu thuật và tiên lượng bệnh...,Bài báo mô tả trường hợp bệnh Rosai-Dorfman ng...,Quản lý điều trị và theo dõi dài hạn bệnh Rosa...,Khóa học này tập trung vào các lựa chọn điều t...

In [15]:
# đếm số NaN
nan_count = df['intruction'].isna().sum()
print("Số NaN:", nan_count)

# đếm số chuỗi rỗng ''
empty_str_count = (df['intruction'] == '').sum()
print("Số chuỗi rỗng:", empty_str_count)

# tổng cộng giá trị rỗng
total_missing = nan_count + empty_str_count
print("Tổng số giá trị rỗng:", total_missing)

Số NaN: 1105
Số chuỗi rỗng: 0
Tổng số giá trị rỗng: 1105

In [16]:
most_common = df['intruction'].value_counts().idxmax()
count = df['intruction'].value_counts().max()

print("Giá trị xuất hiện nhiều nhất:", most_common)
print("Số lần xuất hiện:", count)

Giá trị xuất hiện nhiều nhất: Chatbot y khoa chuyên về y khoa, cung cấp thông tin và tư vấn lâm sàng dựa trên ICD-10.
Số lần xuất hiện: 16740

In [17]:
# thay NaN và chuỗi rỗng bằng most_common
df['intruction'] = df['intruction'].fillna(most_common)

In [18]:
df_diagnosis = df
df_diagnosis

,intruction,icd_10,icd_10/title,question,symptom,diagnosis,document/title,document/description,cme/title,cme/description
0,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",N39.3,Tiểu không kiểm soát do gắng sức ở nữ giới,Các triệu chứng điển hình của tiểu không kiểm ...,Các triệu chứng và dấu hiệu lâm sàng bao gồm: ...,Chẩn đoán tiểu không kiểm soát do gắng sức ở n...,Hướng dẫn chẩn đoán và quản lý tiểu không kiểm...,Tài liệu này cung cấp các tiêu chí chẩn đoán t...,Cập nhật chẩn đoán phân biệt và nguyên nhân gâ...,Khóa học đào tạo y khoa liên tục này nhằm nâng...
1,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",N39.3,Tiểu không kiểm soát do gắng sức ở nữ giới,Những chỉ định lâm sàng nào cho phẫu thuật TOT...,Các triệu chứng gợi ý chỉ định phẫu thuật TOT ...,Chỉ định phẫu thuật TOT được cân nhắc cho nhữn...,Nghiên cứu về chỉ định phẫu thuật TOT trong đi...,Tài liệu này trình bày các phát hiện từ một ng...,Kỹ thuật phẫu thuật TOT và quản lý biến chứng ...,Khóa học này cung cấp kiến thức chuyên sâu về ...
2,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",N39.3,Tiểu không kiểm soát do gắng sức ở nữ giới,"Tiểu không kiểm soát là gì, tần suất mắc bệnh ...","Tiểu không kiểm soát, theo định nghĩa của Hiệp...",Tiểu không kiểm soát do gắng sức là một tình t...,Dịch tễ học và tác động của tiểu không kiểm so...,"Tài liệu này nghiên cứu sâu về định nghĩa, phạ...",Phân tích gánh nặng bệnh tật và tác động tâm l...,Khóa học này tập trung vào việc đánh giá gánh ...
3,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",N39.3,Són tiểu gắng sức ở nữ giới,Són tiểu gắng sức ở nữ giới là gì và phẫu thuậ...,Bệnh nhân có biểu hiện rò rỉ nước tiểu không c...,Chẩn đoán són tiểu gắng sức ở nữ giới (ICD-10:...,Nghiên cứu về chỉ định phẫu thuật TOT điều trị...,Tài liệu này trình bày kết quả của một nghiên ...,Cập nhật chẩn đoán và điều trị són tiểu gắng s...,Khóa học CME này cung cấp kiến thức toàn diện ...
4,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",N39.3,Són tiểu gắng sức ở nữ giới,Những chỉ định và chống chỉ định cụ thể cho ph...,Bệnh nhân đã được chẩn đoán xác nhận mắc són t...,Chẩn đoán són tiểu gắng sức (ICD-10: N39.3) là...,Chỉ định phẫu thuật TOT trong điều trị són tiể...,Tài liệu này tổng hợp các hướng dẫn lâm sàng v...,Phẫu thuật nâng đỡ niệu đạo giữa: Kỹ thuật TOT...,Khóa học này tập trung chuyên sâu vào kỹ thuật...
...,...,...,...,...,...,...,...,...,...,...
20645,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",D76.3,Các hội chứng mô bào khác,Đặc điểm mô bệnh học và các dấu ấn hóa mô miễn...,"Bệnh nhân nam, 54 tuổi, có tổn thương nốt đỏ b...",Chẩn đoán bệnh Rosai-Dorfman nguyên phát của d...,BỆNH ROSAI -DORFMAN NGUYÊN PHÁT CỦA DA VÙNG LƯ...,Bài báo cáo trường hợp lâm sàng về bệnh Rosai-...,Ứng dụng hóa mô miễn dịch trong chẩn đoán phân...,Khóa học này cung cấp cái nhìn tổng quan và ch...
20646,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",D76.3,Các hội chứng mô bào khác,Bệnh Rosai-Dorfman nguyên phát của da thường đ...,Bệnh nhân nam 54 tuổi với tổn thương dạng nốt ...,Sau khi chẩn đoán xác định bệnh Rosai-Dorfman ...,BỆNH ROSAI -DORFMAN NGUYÊN PHÁT CỦA DA VÙNG LƯ...,Báo cáo trường hợp lâm sàng minh họa một ca bệ...,Tiếp cận điều trị và tiên lượng các thể bệnh R...,Khóa học này khám phá các phương pháp điều trị...
20647,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",D76.3,Các hội chứng mô bào khác,Làm thế nào để chẩn đoán bệnh Rosai-Dorfman ng...,"Tổn thương da (nốt, mảng, sẩn) ảnh hưởng lớp b...",Chẩn đoán xác định bệnh Rosai-Dorfman nguyên p...,Đặc điểm mô bệnh học và hóa mô miễn dịch trong...,Tài liệu này trình bày chi tiết các tiêu chí c...,Tiếp cận chẩn đoán mô bệnh học và hóa mô miễn ...,Khóa học đào tạo y khoa liên tục này cung cấp ...
20648,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",D76.3,Các hội chứng mô bào khác,Bệnh Rosai-Dorfman nguyên phát ở da khác biệt ...,Đối với Rosai-Dorfman nguyên phát ở da: tuổi t...,Bệnh Rosai-Dorfman nguyên phát ở da được phân ...,"Phân loại và đặc điểm dịch tễ, lâm sàng của cá...",Tài liệu này phân tích sự khác biệt về dịch tễ...,Cập nhật phân loại và chiến lược chẩn đoán phâ...,Khóa học cung cấp cái nhìn tổng quan về hệ thố...
20649,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",D76.3,Các hội chứng mô bào khác,Sau khi chẩn đoán bệnh Rosai-Dorfman nguyên ph...,"Bệnh nhân có tổn thương da dạng nốt, mảng hoặc...",Chẩn đoán bệnh Rosai-Dorfman nguyên phát ở da ...,Kết quả điều trị phẫu thuật và tiên lượng bệnh...,Bài báo mô tả trường hợp bệnh Rosai-Dorfman ng...,Quản lý điều trị và theo dõi dài hạn bệnh Rosa...,Khóa học này tập trung vào các lựa chọn điều t...

In [19]:
df = pd.read_excel("../icd-10/icd10_processed.xlsx")
df

,STT CHƯƠNG,MÃ CHƯƠNG,TÊN NHÓM CHÍNH,MÃ BỆNH,TÊN BỆNH
0,I,A00-B99,Bệnh nhiễm trùng đường ruột,A00,Bệnh tả
1,I,A00-B99,Bệnh nhiễm trùng đường ruột,A00.0,"Bệnh tả do Vibrio cholerae 01, typ sinh học ch..."
2,I,A00-B99,Bệnh nhiễm trùng đường ruột,A00.1,"Bệnh tả do Vibrio cholerae 01, typ sinh học eltor"
3,I,A00-B99,Bệnh nhiễm trùng đường ruột,A00.9,"Bệnh tả, không đặc hiệu"
4,I,A00-B99,Bệnh nhiễm trùng đường ruột,A01,Bệnh thương hàn và phó thương hàn
...,...,...,...,...,...
12214,XXII,U00-U99,Kháng các thuốc kháng sinh và chống ung thư,U84.3,Kháng (các) thuốc chống lao
12215,XXII,U00-U99,Kháng các thuốc kháng sinh và chống ung thư,U84.7,Kháng đa thuốc kháng vi sinh vật
12216,XXII,U00-U99,Kháng các thuốc kháng sinh và chống ung thư,U84.8,Kháng thuốc kháng vi sinh vật xác định khác
12217,XXII,U00-U99,Kháng các thuốc kháng sinh và chống ung thư,U84.9,Kháng các thuốc kháng vi sinh vật không xác định
12218,XXII,U00-U99,Kháng các thuốc kháng sinh và chống ung thư,U85,Kháng các thuốc kháng ung thư

In [20]:
merged = df.merge(
    df_diagnosis,
    how="outer",
    left_on="MÃ BỆNH",
    right_on="icd_10"
)

In [21]:
merged

,STT CHƯƠNG,MÃ CHƯƠNG,TÊN NHÓM CHÍNH,MÃ BỆNH,TÊN BỆNH,intruction,icd_10,icd_10/title,question,symptom,diagnosis,document/title,document/description,cme/title,cme/description
0,I,A00-B99,Bệnh nhiễm trùng đường ruột,A00,Bệnh tả,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,I,A00-B99,Bệnh nhiễm trùng đường ruột,A00.0,"Bệnh tả do Vibrio cholerae 01, typ sinh học ch...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,I,A00-B99,Bệnh nhiễm trùng đường ruột,A00.1,"Bệnh tả do Vibrio cholerae 01, typ sinh học eltor",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,I,A00-B99,Bệnh nhiễm trùng đường ruột,A00.9,"Bệnh tả, không đặc hiệu",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,I,A00-B99,Bệnh nhiễm trùng đường ruột,A01,Bệnh thương hàn và phó thương hàn,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30855,XXI,Z00-Z99,Những người có nguy cơ sức khỏe tiềm ẩn liên q...,Z99.4,Lệ thuộc vào tim nhân tạo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30856,XXI,Z00-Z99,Những người có nguy cơ sức khỏe tiềm ẩn liên q...,Z99.8,Phụ thuộc vào các thiết bị và dụng cụ khác,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",Z99.8,Phụ thuộc vào các máy và thiết bị hỗ trợ khác,Kỹ thuật ECMO (Oxy hóa máu qua màng ngoài cơ t...,Các triệu chứng lâm sàng cho thấy bệnh nhân cầ...,ECMO (Extracorporeal Membrane Oxygenation) là ...,Kỹ thuật Oxy hóa máu qua màng ngoài cơ thể (EC...,"Tổng quan về nguyên lý hoạt động, phân loại (V...",ECMO cơ bản: Nguyên lý và thực hành lâm sàng t...,Khóa học này cung cấp kiến thức nền tảng về kỹ...
30857,XXI,Z00-Z99,Những người có nguy cơ sức khỏe tiềm ẩn liên q...,Z99.8,Phụ thuộc vào các thiết bị và dụng cụ khác,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",Z99.8,"Phụ thuộc vào các máy và thiết bị hỗ trợ khác,...",Những nhóm bệnh nhân nào có nguy cơ cao mắc nh...,Các bệnh nhân có nguy cơ cao mắc nhiễm khuẩn b...,Các bệnh nhân tại khoa hồi sức tích cực được c...,THỰC TRẠNG NHIỄM KHUẨN BỆNH VIỆN TẠI CÁC KHOA ...,Nghiên cứu này làm rõ các yếu tố nguy cơ và bố...,An toàn người bệnh và phòng ngừa nhiễm khuẩn t...,Khóa học cung cấp kiến thức và kỹ năng về các ...
30858,XXI,Z00-Z99,Những người có nguy cơ sức khỏe tiềm ẩn liên q...,Z99.9,Phụ thuộc vào thiết bị và dụng cụ không xác định,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30859,NaN,NaN,NaN,NaN,NaN,"Chatbot y khoa chuyên về y khoa, cung cấp thôn...",NaN,NaN,NaN,NaN,Việc chẩn đoán AML sau hóa trị đòi hỏi sự cảnh...,BỆNH BẠCH CẦU TỦY CẤP TÍNH SAU HÓA TRỊ: BÁO CÁ...,Bài báo này cung cấp các báo cáo ca lâm sàng t...,Chiến lược sàng lọc và theo dõi bệnh bạch cầu ...,Khóa học này trang bị cho bác sĩ kiến thức về ...

In [22]:
df = merged.dropna(subset=['MÃ BỆNH'])
df = df[df.isna().any(axis=1)]

In [23]:
df.to_excel("SVYKHOA_dataset_diagnosis_cleaned.xlsx", index=False)

In [24]:
df

,STT CHƯƠNG,MÃ CHƯƠNG,TÊN NHÓM CHÍNH,MÃ BỆNH,TÊN BỆNH,intruction,icd_10,icd_10/title,question,symptom,diagnosis,document/title,document/description,cme/title,cme/description
0,I,A00-B99,Bệnh nhiễm trùng đường ruột,A00,Bệnh tả,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,I,A00-B99,Bệnh nhiễm trùng đường ruột,A00.0,"Bệnh tả do Vibrio cholerae 01, typ sinh học ch...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,I,A00-B99,Bệnh nhiễm trùng đường ruột,A00.1,"Bệnh tả do Vibrio cholerae 01, typ sinh học eltor",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,I,A00-B99,Bệnh nhiễm trùng đường ruột,A00.9,"Bệnh tả, không đặc hiệu",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,I,A00-B99,Bệnh nhiễm trùng đường ruột,A01,Bệnh thương hàn và phó thương hàn,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30842,XXI,Z00-Z99,Những người có nguy cơ sức khỏe tiềm ẩn liên q...,Z99,Tình trạng phụ thuộc vào các thiết bị và dụng ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30843,XXI,Z00-Z99,Những người có nguy cơ sức khỏe tiềm ẩn liên q...,Z99.0,Phụ thuộc máy hút,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30854,XXI,Z00-Z99,Những người có nguy cơ sức khỏe tiềm ẩn liên q...,Z99.3,Phụ thuộc vào xe lăn,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30855,XXI,Z00-Z99,Những người có nguy cơ sức khỏe tiềm ẩn liên q...,Z99.4,Lệ thuộc vào tim nhân tạo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30858,XXI,Z00-Z99,Những người có nguy cơ sức khỏe tiềm ẩn liên q...,Z99.9,Phụ thuộc vào thiết bị và dụng cụ không xác định,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
import pandas as pd
import google.generativeai as genai
import time
import os
from tqdm import tqdm
import json
# Cấu hình API Key
genai.configure(api_key="AIzaSyAk_vq1Q19RCkbHq1bNCELRiHZUi-89neA")  # <-- Nhớ điền API key ở đây

# Khởi tạo model
model = genai.GenerativeModel(model_name='models/gemini-2.5-flash')

# File input và output
input_file = "SVYKHOA_dataset_diagnosis_cleaned.xlsx"
output_file = "gen_SVYKHOA_dataset_diagnosis.xlsx"

# Đọc dữ liệu đầu vào
try:
    df_input = pd.read_excel(input_file)
    df_input = df_input[['TÊN NHÓM CHÍNH','MÃ BỆNH','TÊN BỆNH']].dropna().reset_index(drop=True)
    print(f"Đã đọc file Excel với {len(df_input)} dòng văn bản.")
except Exception as e:
    print(f"Lỗi khi đọc file Excel: {str(e)}")
    exit()

# Tạo DataFrame kết quả
result_columns = [
    "intruction", "question", "symptom", "diagnosis",
    "document/title",  "document/description",
    "cme/title", "cme/description"
]
if os.path.exists(output_file):
    df_result = pd.read_excel(output_file)
else:
    df_result = pd.DataFrame(columns=result_columns)

# Prompt Template mới
prompt_template = """
Bạn là một chuyên gia y tế chuyên về y khoa. Nhiệm vụ của bạn là tạo dữ liệu huấn luyện dành cho một **chatbot y khoa chuyên về y khoa** nhằm giúp chatbot phản hồi người dùng một cách chính xác, khoa học và đáng tin cậy theo chuẩn ICD-10 của Bộ Y tế Việt Nam.
Dựa vào các thông tin sau:
- TÊN NHÓM CHÍNH: {group_name}
- MÃ BỆNH: {disease_code}
- TÊN BỆNH: {disease_name}
Biết: 
- Tên nhóm chính là nhóm bệnh đại diện cho mã icd10 và loại bệnh đấy
- Mã bệnh là mã icd10 chính xác cho loại bệnh đấy
- Tên bệnh là tên bệnh chính xác cho loại bệnh đấy
Hãy sinh ra một **DANH SÁCH GỒM 5 ĐỐI TƯỢNG JSON** chứa đầy đủ TẤT CẢ các trường dưới đây. Tuyệt đối không được bỏ trống bất kỳ trường nào. Nếu đoạn văn không nêu rõ thông tin, bạn được phép **bổ sung hợp lý dựa trên kiến thức y khoa chính thống**, nhưng KHÔNG được bịa đặt hoặc sử dụng thông tin sai sự thật.
**Mục tiêu**: Dữ liệu được tạo ra sẽ được dùng để huấn luyện một **mô hình chatbot y tế**, vì vậy tất cả thông tin cần:
- Chính xác về mặt y học.
- Bám sát nội dung đoạn văn hoặc kiến thức y khoa phổ biến đã được xác thực (ví dụ: WHO, Bộ Y tế, giáo trình nha khoa).
- Có giá trị hướng dẫn, giải thích rõ ràng, có thể dùng để **tư vấn lâm sàng cho người dùng cuối**.
**Yêu cầu đặc biệt**:
- Nếu đoạn văn có đề cập đến các **chỉ số lâm sàng** như độ sâu túi lợi, chỉ số mảng bám, số răng tổn thương, mức độ đau... thì **phải đưa các con số và dữ liệu đó vào `symptom` và `diagnosis`** để tăng độ chính xác cho chatbot.
- `symptom` và `diagnosis` phải viết theo ngôn ngữ chuyên môn, **khoa học, cụ thể, không chung chung**, đủ để một bác sĩ hoặc chatbot sử dụng để diễn giải cho người bệnh.
Các trường cần điền:
- "intruction": Mô tả ngắn gọn về nhiệm vụ của chatbot, ví dụ: "Chatbot y khoa chuyên về y khoa, cung cấp thông tin và tư vấn lâm sàng dựa trên ICD-10."
- "question": Một câu hỏi y khoa phù hợp với **nội dung bài viết và câu trả lời**, tập trung vào chẩn đoán hoặc điều trị y khoa (giống như người dùng hay bác sỹ trẻ hỏi chatbot).
- "symptom": Các triệu chứng hoặc dấu hiệu lâm sàng được nêu trong bài, hoặc suy luận có cơ sở khoa học. **Bao gồm cả các chỉ số định lượng nếu có** như: túi nha chu 6mm, PI=2.2, v.v.
- "diagnosis": Chẩn đoán nha khoa chi tiết, có thể phân loại theo mức độ bệnh hoặc giai đoạn nếu phù hợp. **Phải có cơ sở y khoa vững chắc** và dùng thông số hỗ trợ chẩn đoán nếu có.
- "document/title": Tiêu đề tài liệu y khoa liên quan đến nội dung đoạn văn.
- "document/description": Mô tả ngắn gọn tài liệu tham khảo, nêu rõ mục đích hoặc giá trị ứng dụng.
- "cme/title": Tiêu đề khóa học đào tạo y khoa liên tục (CME) liên quan đến chủ đề trong đoạn văn.
- "cme/description": Mô tả ngắn về khóa học CME, giúp chatbot hiểu và phản hồi như một trợ lý học thuật chuyên ngành.
Lưu ý:- Chỉ xuất đầu ra dưới dạng đối tượng JSON hợp lệ. KHÔNG thêm bất kỳ mô tả, lời giải thích hoặc đoạn văn nào khác bên ngoài JSON.
      - Không được bổ trống bất kỳ trường nào trong đối tượng JSON.
"""



# Hàm sinh dữ liệu
def generate_with_retry(prompt, max_retries=3):
    for attempt in range(max_retries):
        try:
            response = model.generate_content(prompt)
            if response.text:
                return response
        except Exception as e:
            if attempt < max_retries - 1:
                wait_time = (attempt + 1) * 5
                print(f"Lỗi, thử lại sau {wait_time}s... (Lần {attempt + 1})")
                time.sleep(wait_time)
            else:
                print(f"Lỗi sau {max_retries} lần thử: {str(e)}")
                return None
    return None

# Hàm xử lý và lưu
def process_and_save(response, disease_code):
    try:
        cleaned = response.text.replace('```json', '').replace('```', '').strip()
        data_list = json.loads(cleaned)

        if not isinstance(data_list, list):
            raise ValueError("Kết quả không phải là danh sách JSON.")

        global df_result
        for data in data_list:
            new_row = {
                "intruction": data.get("intruction", ""),
                "question": data.get("question", ""),
                "icd10": disease_code,
                "symptom": data.get("symptom", ""),
                "diagnosis": data.get("diagnosis", ""),
                "document/title": data.get("document/title", ""),
                "document/description": data.get("document/description", ""),
                "cme/title": data.get("cme/title", ""),
                "cme/description": data.get("cme/description", "")
            }
            df_result.loc[len(df_result)] = new_row
        return True
    except Exception as e:
        print(f"\nLỗi xử lý response: {str(e)}")
        print(f"Response gốc: {response.text[:200]}...")
        return False

# Thiết lập số dòng xử lý
start_row = len(df_result)
end_row = len(df_input)
processed_count = 0
start_time = time.time()

# Vòng lặp xử lý
for index in tqdm(range(start_row, end_row)):
    row = df_input.iloc[index]
    retries = 0

    while retries < 3:
        try:
            group_name = row['TÊN NHÓM CHÍNH'].strip()
            disease_code = row['MÃ BỆNH'].strip()
            disease_name = row['TÊN BỆNH'].strip()
            prompt = prompt_template.format(
                group_name=group_name,
                disease_code=disease_code,
                disease_name=disease_name
            )
            response = generate_with_retry(prompt)

            if response and process_and_save(response, disease_code):
                processed_count += 1
                df_result.to_excel(output_file, index=False)
                time.sleep(2)
                break
            else:
                retries += 1
                print(f"Retry dòng {index} - Lần {retries}")
                time.sleep(3)

        except Exception as e:
            print(f"\nLỗi dòng {index}: {str(e)}")
            retries += 1
            time.sleep(3)

# Lưu cuốil
df_result.to_excel(output_file, index=False)
total_time = (time.time() - start_time) / 60
print(f"\nHoàn thành! Đã xử lý {processed_count} dòng.")
print(f"Thời gian chạy: {total_time:.2f} phút")
print(f"File kết quả: {output_file}")

Đã đọc file Excel với 10214 dòng văn bản.

  0%|          | 1/10214 [01:15<213:38:50, 75.31s/it]

KeyboardInterrupt: